apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backendappnodejs
  name: backendappnodejs
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: backendappnodejs
  type: LoadBalancer
status:
  loadBalancer: {}
